version: '3'

services:
  webapp:
    build: ./webapp
    ports:
      - 4000:80

  dbserver:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: e347h43cve89
      MYSQL_DATABASE: ssp_ss_container
    volumes:
      - ./sqldump:/docker-entrypoint-initdb.d
    ports:
      - 4500:3306

  dbadmin:
    image: phpmyadmin:5-apache
    restart: always
    environment:
      PMA_HOST: dbserver
    ports:
      - 4600:80
